services:
  app:
    image: nginx:alpine
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      default:
      reverse-proxy-network:
        aliases:
          - aaa-container

networks:
  reverse-proxy-network:
    external: true