version: "3"

services:
  nginx:
    container_name: nginx
    build:
      ./nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d